<?php 
$_product = $block->getProduct();
$special = $_product->getSpecialToDate();
?>

<script type="text/x-magento-init">
{
    "*": {
            "Magento_Ui/js/core/app": {
            "components": {
                "timer-scope": {
                    "component": "Adam_Countdown/js/knockout-timer",
                    "date": "<?= $special;?>"
                }
            }
        }
    }
}
</script>

<div data-bind="scope: 'timer-scope'">
	<!-- ko template: getTemplate() --><!-- /ko -->
</div>